workflows:
    android-workflow-id:
        name: Android Sample Workflow
        max_build_duration: 120  
        # .......
        # .......  
    ios-workflow-id:
        name: iOS Sample Workflow
        max_build_duration: 120